# Generated by Django 3.1.4 on 2020-12-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('statement_name', models.CharField(max_length=10000)),
                ('languages', models.CharField(max_length=10000)),
                ('memory_limit', models.CharField(max_length=10000)),
                ('time_limit', models.CharField(max_length=10000)),
            ],
        ),
    ]
