# Generated by Django 3.1.4 on 2020-12-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competing', '0002_submissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='submissions',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='id',
        ),
        migrations.AddField(
            model_name='submissions',
            name='submission_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
