# Generated by Django 3.1.4 on 2020-12-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competing', '0006_auto_20201207_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_name',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
